### ISSUE TITLE
Question: RecordSerializer::decodeMessage

### ISSUE THREAD

**Issue by nick-zh** [flix-tech/avro-serde-php#28]
Hey @tPl0ch 

I have the following scenario, i have a consumer that is consuming from multiple topics (meaning different schemas). Now lets say the consumer needs to have fixed versions for some of them.
From what i see, i would need to duplicate the first few lines of `decodeMessage`, namly:
```
$decoded = decode($binaryMessage);
$schemaId = valueOf($decoded->bind($this->schemaIdGetter));
```
To check if i have a fixed version for a specific schemaId. Since i don't want to decode twice, i was thinking about maybe splitting `decodeMessage` in two parts.
I was thinking something in the line of `getValidatedMessage`,
but not sure if this is the best approach...
Any input would be highly appreciated

**Comment by tPl0ch** [comment]
@nick-zh I have to admit that I have problems understanding what you mean with *fixed* versions. Could you give me a little bit more detail? In my understanding the schema version should always be encoded in the message, and then managing a mapping between schema ID and schema is trivial (this actually happens in the `CachedSchemaRegistry`).

**Comment by nick-zh** [comment]
@tPl0ch true, but i am actually free to read the message with a different version than the one encoded in the message.

**Comment by tPl0ch** [comment]
@nick-zh OK I get it now. The problem is that the `RecordSerializer` has the possibility to pass in a reader schema, but it does not know if that reader schema should be applied to a given binary message due to being subscribed to multiple topics.

While the function is called `decode` it is not actually *avro decoding* the message, but just splitting the binary string into the protocol chunks. I noted a memo to rename this function to something along the lines of `extractProtocolMembersFromBinary`. In other words there should be no transformation and just cutting the binary string into chunks which should be super fast.

This also means that you can safely re-use the first result of `decode` to extract the schema ID.

Does this help you?

**Comment by nick-zh** [comment]
@tPl0ch absolutely helps, thanks a lot for the insight!
